
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

    public class Musica extends javax.swing.JFrame {

        DefaultListModel modelo = new DefaultListModel();
        ArrayList<String> listaMusica = new ArrayList<>();

        /**
         * Creates new form Musica
         */
        public Musica() {
            initComponents();
            JlistCanciones.setModel(modelo);
            listaMusica.add("Que vida la mia");
            listaMusica.add("Canela");
            listaMusica.add("Nublado");
            listaMusica.add("Believer");
            listaMusica.add("Neverita");
            llenarListaMusica();

        }

        public void llenarListaMusica() {
            modelo.removeAllElements();
            for (int i = 0; i < listaMusica.size(); i++) {
                modelo.addElement(listaMusica.get(i));
            }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            JlistCanciones = new javax.swing.JList<>();
            btnAgregar = new javax.swing.JButton();
            btnBuscar = new javax.swing.JButton();
            btnEliminar = new javax.swing.JButton();
            btnSalir = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(255, 102, 102));

            jPanel1.setBackground(new java.awt.Color(255, 153, 204));

            jLabel1.setFont(new java.awt.Font("Comfortaa Light", 3, 18)); // NOI18N
            jLabel1.setText("MUSICA");

            jScrollPane1.setViewportView(JlistCanciones);

            btnAgregar.setText("Agregar");
            btnAgregar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAgregarActionPerformed(evt);
                }
            });

            btnBuscar.setText("Buscar");
            btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscarActionPerformed(evt);
                }
            });

            btnEliminar.setText("Eliminar");
            btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEliminarActionPerformed(evt);
                }
            });

            btnSalir.setText("Salir");
            btnSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSalirActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addGap(220, 220, 220))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(89, 89, 89)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(61, 61, 61))
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(30, 30, 30)
                                                    .addComponent(btnAgregar)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnBuscar)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnEliminar)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnSalir)))
                                    .addContainerGap(32, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
            // TODO add your handling code here:
            String nombreCanciones = JOptionPane.showInputDialog("Escribe una cancion a buscar");
            if(nombreCanciones.equals("") || nombreCanciones == null){
                return;
            }

            if(listaMusica.contains(nombreCanciones)){
                JOptionPane.showMessageDialog(this, "Si se encuentra la cancion");
            } else{
                JOptionPane.showMessageDialog(this, "No se encuentra la cancion");
            }
        }//GEN-LAST:event_btnBuscarActionPerformed

        private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
            // TODO add your handling code here:
            System.exit(0);
        }//GEN-LAST:event_btnSalirActionPerformed

        private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
            // TODO add your handling code here:
            String nombreCanciones = JOptionPane.showInputDialog("Escribe un nombre de una cancion:");
            if(nombreCanciones.equals("") || nombreCanciones == null){
                return;
            }
            listaMusica.add(nombreCanciones);
            llenarListaMusica();
        }//GEN-LAST:event_btnAgregarActionPerformed

        private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
            // TODO add your handling code here:
            String nombreCanciones = JOptionPane.showInputDialog("Escribe una cancion a borrar: ");
            if(nombreCanciones.equals("") || nombreCanciones == null){
                return;
            }
            Iterator<String> iterador = listaMusica.iterator();
            while(iterador.hasNext()){
                if(nombreCanciones.equals(iterador.next())){
                    iterador.remove();
                    JOptionPane.showMessageDialog(this, "La Cancion se ha eliminado");
                }
            }
            llenarListaMusica();
        }//GEN-LAST:event_btnEliminarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Musica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Musica().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JList<String> JlistCanciones;
        private javax.swing.JButton btnAgregar;
        private javax.swing.JButton btnBuscar;
        private javax.swing.JButton btnEliminar;
        private javax.swing.JButton btnSalir;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
    }


